function raw_sleepscoringdata = io_main(mdfExtract_folderpath)
% This function requires folder directory input
% Input folder contains 1. analog.txt, 2. info.txt, 3. eye.avi, 4. whisker.avi, 5.motion.txt, and 6.two photon imaging ch1 and 7.ch2 data
% Those files are generated by mdfExtractor by H.Lee convert .mdf file recorded by sutter resonant two photon microscope to general format
    % Among the files in folder this function read 1.analog.txt, 2.info.txt, 3.eye.avi, 4.whisker.avi 
    path_struct = struct();
    path_struct.analog = pathfinder(mdfExtract_folderpath,'*analog.txt'); % 1
    path_struct.info = pathfinder(mdfExtract_folderpath, '*info.txt'); % 2
    path_struct.eye = pathfinder(mdfExtract_folderpath, '*eye.avi'); % 3
    path_struct.whisker = pathfinder(mdfExtract_folderpath, '*whisker.avi'); % 4

    raw_sleepscoringdata = struct();
    raw_sleepscoringdata.analog = io_loadanalog(path_struct.analog);
    raw_sleepscoringdata.eye = io_loadavi(path_struct.eye);
    raw_sleepscoringdata.whisker = io_loadavi(path_struct.whisker);
    raw_sleepscoringdata.info = io_loadinfo_hl(path_struct.info);
end
function matchedpath = pathfinder(folder_path, name_pattern)
    dirstruct = dir(fullfile(folder_path, name_pattern));
    matchedpath = fullfile(dirstruct.folder, dirstruct.name);
end